[tool.poetry]
name = "swe-lite-ra-aid"
version = "0.1.0"
description = "SWE Bench Lite for ra-aid agent"
authors = ["Ariel Frischer <arielfrischer@gmail.com>"]
readme = "README.md"
packages = [{include = "swe_lite_ra_aid"}]

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
ra-aid = "^0.12.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

